[package]
name = "wireshart-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
pcap-parser = "0.15.0"
clap = { version = "4.0", features = ["derive"] }
packet-parser = { path = "../packet-parser" }

[[bin]]
name = "wireshart"
path = "src/main.rs"
